version: '3.5'

services:
  test:
    image: elixir
    entrypoint: code/exec.sh
    command: data/validate.sh
    volumes:
      - ./../../data/minimal:/algorithm/data
      - .:/algorithm/code
    working_dir: /algorithm
